# Generated by Django 5.2.1 on 2025-09-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_project_options_alter_project_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='employee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
