# Generated by Django 5.2.1 on 2025-09-10 07:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_expense_employee_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_terms', models.CharField(choices=[('10_advance', '10% Advance'), ('20_advance', '20% Advance'), ('30_advance', '30% Advance'), ('40_advance', '40% Advance'), ('50_advance', '50% Advance'), ('full_advance', '100% Advance'), ('on_delivery', 'On Delivery'), ('30_days', '30 Days Credit'), ('60_days', '60 Days Credit'), ('90_days', '90 Days Credit')], default='40_advance', max_length=20)),
                ('delivery_terms', models.CharField(choices=[('immediate', 'Immediate'), ('7_days', '7 Days'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('45_days', '45 Days'), ('60_days', '60 Days'), ('custom', 'Custom')], default='15_days', max_length=20)),
                ('freight_charges', models.CharField(choices=[('included', 'Included'), ('excluded', 'Excluded'), ('fob', 'FOB'), ('cif', 'CIF')], default='excluded', max_length=20)),
                ('validity_period', models.CharField(choices=[('7_days', '7 Days'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('45_days', '45 Days'), ('60_days', '60 Days'), ('90_days', '90 Days')], default='30_days', max_length=20)),
                ('warranty_period', models.CharField(choices=[('no_warranty', 'No Warranty'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('2_years', '2 Years'), ('3_years', '3 Years'), ('5_years', '5 Years'), ('lifetime', 'Lifetime')], default='2_years', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.bank')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('tax_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.taxtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='leads.quotation')),
            ],
        ),
    ]
