# Generated by Django 5.2.1 on 2025-09-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_bank_taxtype_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
