# Generated by Django 5.2.1 on 2025-09-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_quotation_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='ifsc_code',
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
