# Generated by Django 5.1.5 on 2025-11-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_remove_bank_account_number_remove_bank_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('pf_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('upload_photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
            ],
        ),
    ]
