# Generated by Django 5.1.5 on 2025-11-24 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField()),
                ('task_type', models.CharField(choices=[('quotation_submitted', 'Quotation Submitted'), ('payment_follow_up', 'Payment follow up'), ('scrap_machine', 'Scrap Machine'), ('ncp_solution', 'NCP_Solution'), ('ncp_machine', 'NCP_Machine'), ('fmc_amc', 'FMC_AMC'), ('phone_call', 'Phone Call'), ('pts_visit', 'PTS_Visit'), ('citro_clear', 'Citro Clear'), ('pulmonary', 'Pulmonary')], max_length=100)),
                ('description', models.TextField()),
                ('remarks', models.TextField()),
                ('follow_up_date', models.DateField()),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='leads.hospitallead')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='leads.staff')),
            ],
        ),
    ]
